#cloud-config
users:
  - name: ubuntu
    groups: [users, admin]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD # Nussle
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPFdpAR3M9psfrZgTVEdlbMfZTX8O/uZdWOqM1zu7HaWtwWoymzjuub4P0UVaqWvq/dbZivt8lZ7A5pdCWnGAfTMnnc51VZ0/oHcTZa9XWse63mzD7HjMRijIR0/rk3AT6k9oY95YQG0z2pvlHfx2tFl7YgX/FmwHloduEboZntj7JM/nR3Ql7JB2EZXY76fksxYAh5md7yW7ZaXtq58+NFkpqVW0Jp1J5BFOIomQJoKlun6asF0/yIENvMPRyuTh/1OKYF7EbtHgsLXdIiVrTTgzBL2mYmh2Y2cxlxvgY8iBhGFFa6gIDnfwMU92uyGKBpk7Lfmn1a+tVm3/ntkmz aws-key # Held
    sudo: ALL=(ALL) NOPASSWD:ALL
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
write_files:
  - path: /var/www/html/info.php
    content: |
      <?php
      phpinfo();
      ?>
    permissions: "0644"
    owner: www-data:www-data
  - path: /var/www/html/db.php
    content: |
      <?php
      //database
      $servername = "172.31.31.8";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";

      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
              die("Connection failed: " . $conn->connect_error);
      }

      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
              echo($row["Host"] . " / " . $row["User"] . "<br />");
      }
      ?>
    permissions: "0644"
    owner: www-data:www-data
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2